apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
  # Single source
  source:
      repoURL: git@github.com:knuurr/gitops-test.git
      path: manifests/prod/authelia
      targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-authelia
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
