apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr-deployment
  namespace: app-flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      # securityContext:
      #   runAsUser: 2000
      #   runAsGroup: 2000
      #   fsGroup: 2000
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - containerPort: 8191
            protocol: TCP
        resources:
          limits:
            cpu: '2'
            memory: 1536Mi
          requests:
            cpu: '0.5'
            memory: 500Mi
        # env:
        # - name: LOG_LEVEL
        #   value: "info"
        # - name: LOG_HTML
        #   value: "false"
        # - name: CAPTCHA_SOLVER
        #   value: "none"
        # - name: TZ
        #   value: "Europe/Warsaw"
        envFrom:
        - configMapRef:
            name: flaresolverr-env-configmap

  # restartPolicy: Always
