apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
  namespace: app-flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8191
  type: ClusterIP
