apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4tdXNlcg==   # Base64 encoded value for 'admin-user'
  admin-password: YWRtaW4tcGFzc3dvcmQ=   # Base64 encoded value for 'admin-password'
